language: python
python:
  - "3.6.7"

env:
  - TEST_DATABASE_URL="dbname='api_test' host='127.0.0.1' port='5432' user='admin' password='admin123'"

install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary
  - pip install codecov

services:
  - postgresql

notifications:
  email: false
  
before_script:
  - psql -c "CREATE DATABASE api_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres

script:
  - pytest --cov=app tests/

after_success:
  - coveralls
  - codecov