language: python
python:
  - "3.6.7"

# install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

# run pytest and coveralls script
script:
  - pytest --cov=app tests/

# then post the results to coveralls
after_success:
  - coveralls