language: python
python:
  - "3.6.7"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install psycopg2
# command to run tests
services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE api_test;" -U postgres

  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres
script:
  - pytest --cov=app tests/

# then post the results to coveralls
after_success:
  - coveralls